dashboard.tsx:104 Error fetching user data for UID: 24dt4XMu2wegTN4yxACjS5USohw2: FirebaseError: Failed to get document because the client is offline.